apiVersion: batch/v1
kind: Job
metadata:
  name: my-backend-migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: my-backend-migration
          image: my-backend-image
          command: ["your-migration-command"]
      restartPolicy: Never
