---
- name: Ensure only essential services are running
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
  loop:
    - apache2
    - nginx
    - mysql

- name: Harden SSH config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: Restart SSHD
