apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8stest
  name: k8stestservice
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: k8stest
  type: NodePort
status:
  loadBalancer: {}
